### PR TITLE
Add mp-full-platform-generator script

### PR DESCRIPTION
**Pull request by xstefank**
Creates a file like https://github.com/wildfly/certifications/blob/MP4.1/WildFly_26.1.0.Final/microprofile-4.1/microprofile-full-platform.adoc

### CODE REVIEW

**Comment by xstefank** [comment]
@bstansberry fyi, just automation of overall MP Certification process on our side :). Not sure which branch should I push this to.

**Comment by scottmarlow** [comment]
Any ideas for the new branch name and whether it should be specific to MP?

Perhaps we should add two new branches:
1. a new branch called `empty` that can be used to create other branches.
2. a `scripts` branch for sharing scripts between MP + Jakarta EE + whatever.
3. a `mpscripts` or `scriptsmp` branch for MP only.

**Comment by xstefank** [comment]
@scottmarlow if it's going to be used to create other branches shouldn't it be rather something like `MP-base`? Personally I thought that we branch out new MPX+1 branch from MPX (at least for now).

**Comment by xstefank** [comment]
@bstansberry can you merge this please? I am working on WFLY 26.1.2 MP 4.1 certifications

**Review by scottmarlow — APPROVED** [review]

**Pull request merged**
